### ISSUE TITLE
mate with 2 knights is impossible

### ISSUE THREAD

**Issue by tissatussa** [bagaturchess/Bagatur#12]
8/5n2/3n3p/7K/5k2/8/5P1N/8 w - - 0 1

![ncmjcoicikclcjgn](https://user-images.githubusercontent.com/1109281/143765998-2d670da8-9a51-48fc-a177-ac9961e1812a.png)

White to move.
The only thing White can hope for is to draw .. so Nh2-g4xh6 can always be done (in the meantime Black can give no checks) and Black will have lost the only pawn !
But ShashChess, as ALL engines i've tested up to now, fails to find these moves, it played Kg6 .. then Black played Ne5+ : it freely gave the pawn ??  That's why this game ended in a draw, however all engines give Black a high eval (3 or 4), also without the last Black pawn : they are not aware of the  2-N-can-not-win  concept ..

NOTE: give mate with 2 knights has some exception : when the opponent (!) has a pawn on the f-file or c-file (on certain ranks) .. in this diagram this is the case .. but the theory about this is beyond my goal : White should "know" it's a good idea to capture the last pawn.

**Comment by AlexBrunetti** [comment]
"all engines give Black a high eval (3 or 4)" That's not true, Stockfish says 0 for example. Even my engine says just -0.6. And any decent engine having a decent material imbalance evaluation knows that KNNk is draw.

Alex

**Comment by tissatussa** [comment]
also see https://en.wikipedia.org/wiki/Two_knights_endgame here you can read:

_[...] When the defender has a single pawn, the technique (when it is possible) is to block the pawn with one knight, and use the king and the other knight to force the opposing king into a corner or nearby the blocking knight. Then, when the block on the pawn is removed, the knight that was used to block the pawn can be used to checkmate. [...]_

here's a PDF of that page : [Two knights endgame - Wikipedia - en.wikipedia.org.pdf](https://github.com/bagaturchess/Bagatur/files/7613475/Two.knights.endgame.-.Wikipedia.-.en.wikipedia.org.pdf)

**Comment by tissatussa** [comment]
@AlexBrunetti i think you're right .. i did test again, see below .. but not all strong engines give 0.00 or alike .. some engines consider Ng4 but then some of them do NOT capture pawn h6 .. not all (strong) engines seem to know KNNk is a draw ..

![SF Crystal v3 2 NNUE Hybrid](https://user-images.githubusercontent.com/1109281/143768302-de4f6ebc-8e92-4073-8fb9-99146ca2a458.png)


![SF v14 noNNUE](https://user-images.githubusercontent.com/1109281/143768305-6670e38f-df07-40ca-8e8b-0940e60cd661.png)


![SF v14 NNUE](https://user-images.githubusercontent.com/1109281/143768306-0609ba9e-03f9-4547-9027-78ba2aca9ce6.png)


![koivisto_v7 2](https://user-images.githubusercontent.com/1109281/143768307-e64ad566-8335-4547-8f05-9adf1b729aed.png)


![nemorino_v6 08_NNUE](https://user-images.githubusercontent.com/1109281/143768308-7bea9e40-f0b2-41d4-9978-b9d11ce3da22.png)


![pedone_v3 1](https://user-images.githubusercontent.com/1109281/143768310-9a4237d1-9f5c-4741-90f3-7507f6d7674b.png)


![komodo_v13 02_noMCTS](https://user-images.githubusercontent.com/1109281/143768311-9d36d4b1-9a2a-4d5b-998f-e6e60af6c1d0.png)


![rubichess_v2 3dev_noNNUE](https://user-images.githubusercontent.com/1109281/143768313-34fdd3ae-7b0e-4027-8793-df118e48ba43.png)


![rubichess_v2 3dev_NNUE](https://user-images.githubusercontent.com/1109281/143768315-c1f283d7-439f-41ca-a98b-913483b86f68.png)


![fire_v8_NN_noMCTS](https://user-images.githubusercontent.com/1109281/143768317-1c5dff33-6e02-427c-94cc-5d042df39a2b.png)


![shashchess_v20_noNNUE](https://user-images.githubusercontent.com/1109281/143768318-eeec1459-59ff-473b-b6c7-c8b1e4e0cdde.png)


![shashchess_v20_NNUE](https://user-images.githubusercontent.com/1109281/143768320-81d08a20-0f5e-424e-b7a5-eff3b31ec006.png)


![amoeba_v3 3 1](https://user-images.githubusercontent.com/1109281/143768321-e3f63781-9dfe-4d53-be96-a5340af65f27.png)


![ethereal_v13 35_noNNUE](https://user-images.githubusercontent.com/1109281/143768322-c3a645bf-0f03-45bf-8ac5-89744e95b24e.png)


![xiphos_v0 6 1](https://user-images.githubusercontent.com/1109281/143768323-cf5c456f-d6c4-4727-9441-218c5c8a2cae.png)


![berserk_v7_NNUE](https://user-images.githubusercontent.com/1109281/143768324-14249ee0-7152-41a3-af76-e299cf008ee6.png)


![slowchess_v2 7](https://user-images.githubusercontent.com/1109281/143768325-bba780e1-f3c0-47d5-a496-769383227419.png)

**Comment by AlexBrunetti** [comment]
My results are different. For example, Berserk 7 at depth 29 you find -4,17 but I have -0.25:
`position fen 8/5n2/3n3p/7K/5k2/8/5P1N/8 w - - 0 1`
`go infinite`
`...`
`info depth 26 seldepth 45 multipv 1 score cp -41 time 7831 nodes 8929642 nps 1140293 tbhits 0 hashfull 884 pv h5g6 f7e5 g6h6 d6f5 h6h5 f5d4 h2f1 d4f3 f1e3 f3d2 e3g2 f4f5 g2e3 f5e4 h5g5 e5f3 g5f6 f3d4 f6e7 d2b3 e3c4 d4f3 e7e6 e4f4 c4d6 b3c1
d6b7 f3g1 b7d6`
`info depth 27 seldepth 45 multipv 1 score cp -33 lowerbound time 12449 nodes 142
33729 nps 1143363 tbhits 0 hashfull 978 pv h5g6`
`info depth 27 seldepth 45 multipv 1 score cp -33 time 12512 nodes 14288098 nps 1
141951 tbhits 0 hashfull 978 pv h5g6 f7e5 g6h6 d6f5 h6h5 f5d4 h2f1 d4f3 f1e3 f3d
2 e3g2 f4f5 g2e3 f5e4 f2f4 e5d7 e3g2 e4f5 g2e3 f5f4 h5g6 d7c5 e3c4 d2e4 g6f7 f4f
3 f7e7 f3g2 c4d2`
`info depth 28 seldepth 45 multipv 1 score cp -33 time 14711 nodes 16810382 nps 1
142708 tbhits 0 hashfull 994 pv h5g6 f7e5 g6h6 d6f5 h6h5 f5d4 h2f1 d4f3 f1e3 f4e
4 h5h6 e5d3 h6g7 f3d4 g7f6 d3c1 e3c4 e4f4 f6e7 d4f3 e7d7 f4e4 d7e6 e4d4 c4e3 f3d
2 e6e7 c1e2 e7e6 d4e4 e6d6 e2c1`
`info depth 29 seldepth 83 multipv 1 score cp -25 lowerbound time 26380 nodes 305
84771 nps 1159392 tbhits 0 hashfull 1000 pv h5g6`
`info depth 29 seldepth 83 multipv 1 score cp -25 time 26614 nodes 30843148 nps 1
158906 tbhits 0 hashfull 1000 pv h5g6 f7e5 g6h6 d6f5 h6h5 f5d4 h2f1 d4f3 f1e3 f4
e4 h5h6 e5d3 h6g7 f3d4 g7f6 d3c1 e3c4 e4f4 f6e7 d4f3 e7d7 f4e4 d7e6 e4d4 c4e3 f3
d2 f2f4 d4e3 f4f5 d2e4 f5f6 e4c5 e6e7`

How is it possible?

Alex

**Comment by tissatussa** [comment]
@AlexBrunetti you must know that all my screenshots are with MPV 5 (except Xiphos and Koivisto, which do only MPV 1) .. so, the top moves are best.

**Comment by tissatussa** [comment]
Here's another example how many engines do NOT know that winning with only 2 knights is impossible :

![position](https://user-images.githubusercontent.com/1109281/143862941-d9ce431a-3d58-4232-8400-99fff3bb2657.png)

Black to move.
Black MUST do Nf6 to protect the only pawn h7, but many engines like to capture the white knight :

![Bagatur_v2 3](https://user-images.githubusercontent.com/1109281/143863008-0ec36565-1fd3-4184-8f99-6bb2b4a76bcb.png)

---

![SF_v14_NNUE](https://user-images.githubusercontent.com/1109281/143863067-126a8915-d463-42f6-b78c-0a34c487fa8d.png)

---

![Nemorino_v6 08_NNUE](https://user-images.githubusercontent.com/1109281/143863102-0e1219e2-6782-4a22-b5de-fc65c9a16c85.png)

---

![Ethereal_v13 35_noNN](https://user-images.githubusercontent.com/1109281/143863138-8d736b24-1f72-4bba-bbad-d15c0703c5b8.png)

---

![RubiChess_v2 3-dev_no_NNUE](https://user-images.githubusercontent.com/1109281/143863178-b1860f9d-2b36-4bf7-882f-ee3b5f85aab3.png)

---

![Critter_v1 6a](https://user-images.githubusercontent.com/1109281/143863203-398e164a-c82e-401d-9c5a-fe14800ad04f.png)

**Comment by bagaturchess** [comment]
Happy New Year 2022! I wish good health and good mood!
P.S. the version 3.0 is released and your feedback is welcome! ;-) I will close this issue.
