### ISSUE TITLE
Avoid draws : use "Contempt"

### ISSUE THREAD

**Issue by tissatussa** [bagaturchess/Bagatur#15]
Some engines have a special option : the 'contempt' factor.
This is a kind of 'optimism' when playing (=my words).

Recently i found this nice article about this, it also contains some links for more info :

**"08-07-2019 - The Contempt-Coherence factor on Stockfish"**
See https://chess.massimilianogoi.com/articles/08-07-19-The-Contempt-Coherence-factor-on-Stockfish/

Here's an excerpt :

---

_“The Contempt Factor reflects the estimated superiority/inferiority of the program over its opponent. The Contempt factor is assigned as draw score to avoid (early) draws against apparently weaker opponents, or to prefer draws versus stronger opponents otherwise.” – [Chessprogramming Wiki](https://www.chessprogramming.org/Contempt_Factor)_

---

_“I am not exactly sure how the contempt setting works. On one site I read that when the engine starts analyzing from a position it gives a “bonus” in the form of the contempt setting to whichever side is on the move. The result that the evaluation keeps bouncing back and forth and, according to the poster, the transposition table is filled with conflicting evaluation scores.
...
Whatever is going on, when analyzing with Stockfish 10 I have noticed what one person called “a strange yo-yo-effect especially at the beginning of the game” (also referred to as the “roller coaster effect”) that results in wild fluctuations in the evaluation every time a move is actually made on the board. His explanation was, like previously mentioned, it is because the contempt factor is switched back and forth to whichever side has the move.” – [Tartajubow on Chess II blog](http://tartajubow.blogspot.com/2019/03/stockfish-10-contempt-settings.html)_

---

I have no idea how to use contempt or test it (with special positions?), i always just keep the default factor of this option when configuring an engine.
Can contempt be used to avoid draws ?  It seems so, according to the above article ..

**Comment by bagaturchess** [comment]
Hi,

yes, I could add contempt factor option with default value 0, because I think this value should be used in most cases.
If Bagatur has this as UCI option, it will be possible to experiment in different games and positions.
I would be very interested in this results!

Here is the background:
I don't like this heuristic, because from my point of view it is not correct from game theory perspective.
The chess is zero-sum game and white and black players' evaluations must be always equal as numbers but with different sign (e.g. 100 and -100). When we enable contempt factor this will creates issues not only in transposition table, but before that in the search algorithm - the so called search instabilities, kind of randomness and fluctuating scores. This leads to issues which are not reproducible and cannot be fixed.
As a workaround, I implemented this by considering the side to move in the starting position (depth = 0, root search position). When we give contempt bonus, the sign is changed if the side to move is different that the side to move in the starting position. Later, I have removed this logic and disabled the feature to be on the safe side.

From my point, this feature makes no sense for ELO strength if you target ranking list with all engines in the world.
It only should make sense if you target engines with bigger ELO or with smaller ELO - give positive value (+50) when playing with stronger engines in order to tolerate achieving draw. And correspondingly, use negative value against engines with smaller ELO in order to prevent draws.
Which is kind of cheat I think.

This is what is in my mind about this topic, but I never had time to test this in more details ...

Best regards,
Krasimir

**Comment by tissatussa** [comment]
I understand your reasoning. The Contempt factor is just something i always wondered about ..

Regarding this, i lately stumbled upon a UCI option called 'MultiPVMargin' in the (old) Spark v1.0 engine (created by a Dutch man). I found this explanation in a forum post - i may interest you :


_https://chess.stackexchange.com/questions/34967/looking-for-a-chess-engine-that-instead-of-playing-the-best-move-randomly-choose

Looking for a chess engine that instead of playing the best move randomly chooses among the best moves?
- May 4, 2021

---

Of course this should be subjected to some rules; something like "play any move that's not bellow 0,70 the best move", or something similar.

My idea is to use such an engine in order to play some unorthodox openings without needing an opening book.

For example, say I want to play some games as White trying 1.e4 e4 2.a3. I'm sure there are many good moves for black's second move, so I'd like the engine to "choose" from several of them, instead of always playing the best one.

Kudos if this behavior could be limited to a fixed number of moves -so you get some variety in the opening but you want it "full power" on middle and endgame.

---

In the GUI Nibbler you have a setting called "Temperature". The higher the temperature value, the more it allows the engine to play unexpected moves. You can also set temperature decay to X moves, so that after X moves it starts playing best moves again.

You can load any engine you want in Nibbler, but it is designed for NN engines, such as Lc0.

---

There are few engines that are capable of such thing. One name that I can recall is the old Spark UCI engine by Allard Siemelink. Very aggressive engine with twistable attacking parameters.

It has a feature called MultiPVMargin which enables you to set certain number difference between the PV (Principle Variations) measured in centipawn.

For example if your best calculated variation in certain position is measured as +1 for white and you want the engine to play something less "valuable" than that, you can set the MultiPVMargin to a 100 so that the engine looks for a different variation within the 100 centipawn difference._

**Comment by bagaturchess** [comment]
Sounds interesting!

It is just for fun, right?

Because when an engine plays it spends much more time when MultiPV is not set to 1.
So this affects playing strength ...

**Comment by tissatussa** [comment]
for fun and also to know if an engine can find Best Move of a puzzle position, with enough time per # MPV .. so a non-obvious move can become Best Move anyhow, while other engines might never () find the BM .. good pruning saves time also !  Remember several weak engines which always won with black in the 4N position .. they might some good PSTs for the position type, anyhow, i'm curious and it's rather easy to program a beta version .. and soon i can test with WAC lists .. the Python script which i found, can handle MPV and get the top-# Best Moves.

i think it must be possible to develop or find dedicated test positions & sets, to tune the pruning.

How does Bagatur prune the variation trees ?
Does it detect a "position type" or its "parameter spectrum" ?
Or just 2 PSTs for mg & eg ?
[ i might be a noob here .. need for development https://www.bitchute.com/video/Fca66RRRVzmZ/ ]

**Comment by tissatussa** [comment]
> ...don't really understand the terms "position type" or its "parameter spectrum"...

yeah, that's my vision in words.
when my WAC tests begin, my terms shall become more concrete - then they might resemble existing methods.

**Comment by bagaturchess** [comment]
> > ...don't really understand the terms "position type" or its "parameter spectrum"...
> 
> yeah, that's my vision in words. when my WAC tests begin, my terms shall become more concrete - then they might resemble existing methods.

In Bagatur it should be more "parameter spectrum" regrading search algorithm. I now some engines use node types e.g. Stockfish.

One additional remark regarding the move ordering: I have taken the idea from Stockfish as well. It was called Continuation History, if I am not wrong. At least I named it that way in Bagatur. :-)
I believe nobody should spend time on searching for better solution. From my perspective this is the prefect solution for chess.

**Comment by tissatussa** [comment]
> ...nobody should spend time on searching for better solution...

In 1903 many people thought is was impossible a human could fly .. :thinking:

![The first flight of the Wright Flyer, December 17, 1903](https://user-images.githubusercontent.com/1109281/145571519-ffe883fc-ed95-43cb-9509-6ac91f6c44f5.png)

**Comment by bagaturchess** [comment]
Yes, sure!
Of course, if you are interested and want to experiment, than nobody can stop you! :-)
This is just my view, but I have tried many things for move ordering, including weights based on search cut-off statistics. The only thing I didn't tried yet is using NNs for move ordering.

**Comment by bagaturchess** [comment]
Contempt is set to 0 currently, because of the reasons above.

**Comment by bagaturchess** [comment]
Contempt is set to 0 currently, because of the reasons above.
