### ISSUE TITLE
find mate (in 5) with MPV : different eval after very long think ?

### ISSUE THREAD

**Issue by tissatussa** [bagaturchess/Bagatur#17]
I did another experiment with the position of Issue #11 .. indeed Bagatur v3.0 finds the Mate in 5 rather quickly !  Here's the output of SCID with mpv 1 :

![Bagatur_mate_in_5_mpv_1](https://user-images.githubusercontent.com/1109281/147858574-6115f650-3a1a-4a30-a17f-0592c43ddd9f.png)

so, after 5.45 seconds Bagatur finds Mate in 5 !
but when setting mpv 5 SCID shows this :

![Bagatur_mate_in_5_mpv_5](https://user-images.githubusercontent.com/1109281/147858578-a3e21013-ecf5-49ff-a586-15e04b7136b7.png)

after 83 seconds Bagatur finds a mate : it's the Mate in 5.
before that, no other Mate-in-[#] was displayed !?

the Mate in 5 occurs at depth 24, not at 32 like Bagatur v2.3 did ! -see Issue #11
but the 83 seconds seems much too long : why is the calculation / evaluation different when using a mpv like 5 ?

**Comment by bagaturchess** [comment]
This is fixed now.
