### ISSUE TITLE
Bagatur 3.3 - problem

### ISSUE THREAD

**Issue by Krzychumag** [bagaturchess/Bagatur#18]
Hello to the author of the engine Bagatur 3.3. I have a serious problem installing the engine. The problem is described at the link http://talkchess.com/forum3/viewtopic.php?f=2&t=80003 . Can you please help in solving this problem. Thank you very much in advance. 

Kind regards
Krzysztof

**Comment by bagaturchess** [comment]
You need to install java and then run the corresponding exe file or bat file in bin directory.
