### ISSUE TITLE
Failed to load Java virtual machine

### ISSUE THREAD

**Issue by gabrielp10031978** [bagaturchess/Bagatur#21]
Hello Mr,
Please tell me what do I have to install so fix failed to load Java virtual machine problem.
I hope you understand what I said, my English is not so good. 
Thanks.

**Comment by bagaturchess** [comment]
Hi and thanks for reaching out!
If you are using Bagatur_32_1_core.exe, than you have to install 32 bits Java.If you are using Bagatur_64_1_core.exe or Bagatur_64_2+_cores.exe than 64 bits Java must be used.
Please let me know if it works?
Best regards,Krasimir
    On Tuesday, February 28, 2023 at 04:55:16 PM GMT+2, gabrielp10031978 ***@***.***> wrote:  
 
 


Hello Mr,
Please tell me what do I have to install so fix failed to load Java virtual machine problem.
I hope you understand what I said, my English is not so good.
Thanks.

**Comment by gabrielp10031978** [comment]
Thanks for your answer Mr.,
Please gave me the link for Java 64 bit.
Thanks a lot.
