### ISSUE TITLE
Elo is not an acronym

### ISSUE THREAD

**Issue by AlexBrunetti** [bagaturchess/Bagatur#22]
All around the site it's written ELO, but it's a surname, from Arpad Elo, its inventor :)

Alex

**Comment by bagaturchess** [comment]
Hi, nice joke! :-) I hope this is a joke having in mind the ":-)" in your comment?

**Comment by AlexBrunetti** [comment]
It's not a joke. I put the smiley to appear not too serious :)

Alex

**Comment by bagaturchess** [comment]
Thanks for being polite. I understand ELO is surname, but it is widely used as acronym. So, what do you expect by reporting this issue?

**Comment by AlexBrunetti** [comment]
Widely by who?! Acronym of what?! I don't expect anything, it's entirely your choice to correct or leave it :)
Alex

**Comment by bagaturchess** [comment]
Hi Alex,
in google search and chess related sites and articles. Not acronym but abbreviation for chess rating (I lost myself in English :-)).
Anyway, Thanks for letting me know and for the feedback!
Best regards,
Krasimir

**Comment by bagaturchess** [comment]
Hi Alex,

I have fixed the issue in all readme files and count it as resolved. Please let me know if I missed some places.

Best regards,
Krasimir

**Comment by AlexBrunetti** [comment]
> I have fixed the issue in all readme files and count it as resolved. Please let me know if I missed some places.

Fantastic, well done!

Kindest regards,
Alex
