### ISSUE TITLE
configure engine : unclear settings

### ISSUE THREAD

**Issue by tissatussa** [bagaturchess/Bagatur#8]
when adjusting the settings in CuteChess, i see 5 entries and some are unclear :

* Ownbook : on your GitHub page(s) i see no opening book file .. how should this option be used ?
* SyzygyPath : originally this was "[..]/v2.3/./data/egtb" and i changed it to "[..]/v2.3/data/egtb" which is the same and also works ..
* Opening Mode : 3 choices but it's unclear what they mean .. and does this apply to the Ownbook checkbox ? Note: there's a typo with 2 'nn' ..
* 
![bagatur_cutechess_config](https://user-images.githubusercontent.com/1109281/141463740-5253718d-6722-462a-ae73-84a3641881d2.png)

**Comment by bagaturchess** [comment]
Hi, I have added text to the readme file: https://github.com/bagaturchess/Bagatur/blob/master/README.md
Please let me know if something is missing?
For now I cannot fix the typo with double 'n', because some people may use this option. I have to think about it how to not surprise people negatively by changing the option name ...
Bets regards,
Krasimir

**Comment by tissatussa** [comment]
> Please let me know if something is missing?

_SyzygyPath (type string default \arena_3.5.1\Engines\BagaturEngine.2.3.\data\egtb): path to the syzygy tables._

The default path differs on my PC : in CuteChess, when i click "Restore defaults", it shows [..]/data/egtb
Note: my working directory is "[..]/bin"
I think the prefix "\arena_3.5.1\Engines\BagaturEngine.2.3." is confusing, because users (like me) may have another install path.

You also could explain that these End Game TableBases are a subset, not the full 7-men pack, which can be (freely) downloaded at many places on the internet.

> For now I cannot fix the typo with double 'n' ..

OK, it's a minor detail :-)

Rest is clear, thanks.

**Comment by bagaturchess** [comment]
Hi,

I have corrected the text.
Actually the directory is set to ./data/egtb and its prefix (like \arena_3.5.1\Engines\BagaturEngine.2.3) is added later depending on the path from where you start Bagatur - the working dir. This should work when you start Bagatur with its exe files but will not work when you start it via bat or sh files. So in your case it has to be set.

Best regards,
Krasimir

**Comment by tissatussa** [comment]
Yes, i think the text of the chapter "Syzygy Endgame Tablebases" is now complete and clear. The path to the egtb folder is also clear, here's my launch of Bagatur :

```
~/Apps/ChessEngines/Bagatur/v2.3/bin$ sh ./Bagatur_1core.sh 

***************************************************************************
* Copyright (C) 2005-2022 Krasimir I. Topchiyski (k_topchiyski@yahoo.com) *
*                                                                         *
* Welcome to Bagatur UCI engine, version 2.3                              *
*                                                                         *
* For help, have a look at the UCI protocol definition at:                *
* http://wbec-ridderkerk.nl/html/UCIProtocol.html                         *
***************************************************************************
\>uci
LOG StateManager: exec command 0 > 'uci'
id name Bagatur 2.3
id author Krasimir Topchiyski, Bulgaria
option name Logging Policy type combo default none var single file var multiple files var none
option name OwnBook type check default true
option name Ponder type check default true
option name UCI_AnalyseMode type check default false
option name MultiPV type spin default 1 min 1 max 100
option name SyzygyPath type string default /home/tissatussa/Apps/ChessEngines/Bagatur/v2.3/./data/egtb
option name Openning Mode type combo default most played first var most played first var random intermediate var random full
LOG StateManager: sendUCIOK called
uciok
```

it's a little strange : "[..]/v2.3/./data/egtb" contains a "/./" which could just be "/" . The total path string can even be "../data/egtb" without any prefix, am i right ?  So, go to the parent folder and then into 'data', because 'bin' is the working dir. Nevermind, your path works ..

**Comment by bagaturchess** [comment]
Yes, it works the same way on my setup! :-)
This has to be fixed.
When bat and sh files are used, the default directory for SyzygyPath  is wrong. It should first go one level up in the directory structure and then set it to ./data/egtb. The dot symbol is also redundant here ... it will work with '/data/egtb' as well.
Best regards,
Krasimir
P.S. I have updated readme.md again. Anything else still missing?

**Comment by tissatussa** [comment]
I think it's OK now : the README is clear and complete, and you are aware of some shortcomings -- to be solved .. good luck !

**Comment by bagaturchess** [comment]
Thanks for your collaboration!
Best regards, Krasimir

**Comment by bagaturchess** [comment]
Happy New Year 2022! I wish good health and good mood!
P.S. the readme is updated and I will close the issue
